### PR TITLE
Implement JSON serialization

### PR DESCRIPTION
**Pull request by antogon**
Some users may want to serialize their data in the Postgres native
JSON format so that it can be arbitrarily queried from outside the
associated application at a later time.  They may also want to restrict
the attributes that are serialized (in whitelist form) to avoid
accidentally serializing more data than they intended.  This adds
those features.

### CODE REVIEW

**Comment by Qqwy** [comment]
This is a good idea! :+1: 

I have one bit of feedback, which is about the naming of the configuration field name `:use_json_serialization?`.
It would be better to have a `:serialization_format` field that defaults to `:etf` and can be changed to `:json`. This opens the possibility for even more types of serialization down the road.

**Review by Qqwy — CHANGES_REQUESTED** [review]
All right, let's do this the proper GitHub PR feedback way :slightly_smiling_face: .

I love your PR. I think it is a great feature that might help some people.

To make sure that it is as useful as possible, I request that rather than a `use_json_serialization?` field in the configuration/options, to use a `serialization_format` key (that is either set to `:etf` or `:json`) because that would be more resilient to future change.

**Comment by antogon** [comment]
@Qqwy I've taken your changes.  Not sure if it notifies you when I update here.  Let me know what you think now?

**Comment by Qqwy** [comment]
@antogon Thank you!
Yes, I receive a notification when new changes happen, but thanks for your heads-up nonetheless.

I did not have time earlier, but I'll read your changes and if they are fine, then I'll merge them and release a new version of the library containing them.

**Comment by Qqwy** [comment]
Looks great! :heart_eyes:

**Comment by Qqwy** [comment]
Version 1.2 has been published to Hex.pm! :grinning:

**Comment by antogon** [comment]
@Qqwy Thanks :)

**Pull request merged**
